server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # for client-side routing (React Router)
    try_files $uri /index.html;
  }

  # Optional: serve static assets efficiently
  location ~* \.(?:js|css|jpg|jpeg|gif|png|ico|woff2?|ttf|svg)$ {
    expires 6M;
    access_log off;
    add_header Cache-Control "public";
  }
}
